# Generated by Django 4.1.3 on 2023-08-04 04:20

import comp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('stipend', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('criteria', models.CharField(max_length=1000)),
                ('opening', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Actively Hiring'), (2, 'closed')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to=comp.models.Query.nameFile)),
            ],
        ),
    ]
